

--GUNA TABLE NI DEKAT DALAM KURMA AJWA


-- CUSTOMER
CREATE TABLE CUSTOMER (
    CustID NUMBER PRIMARY KEY,
    CustName VARCHAR2(100) NOT NULL,
    CustEmail VARCHAR2(100),
    CustAddress VARCHAR2(200),
    CustPhoneNum VARCHAR2(20)
);

-- WORKERS
CREATE TABLE WORKERS (
    WorkID NUMBER PRIMARY KEY,
    WorkName VARCHAR2(100) NOT NULL,
    WorkPhoneNum VARCHAR2(20),
    ManagerID NUMBER,
    CONSTRAINT FK_WORKER_MANAGER
        FOREIGN KEY (ManagerID)
        REFERENCES WORKERS(WorkID)
);

-- FULL TIME WORKERS
CREATE TABLE FULL_TIME_WORKERS (
    WorkID NUMBER PRIMARY KEY,
    Salary NUMBER(10,2),
    Bonus_Salary NUMBER(10,2),
    CONSTRAINT FK_FULLTIME_WORKER
        FOREIGN KEY (WorkID)
        REFERENCES WORKERS(WorkID)
);

-- PART TIME WORKERS
CREATE TABLE PART_TIME_WORKERS (
    WorkID NUMBER PRIMARY KEY,
    SalaryPerHr NUMBER(10,2),
    CONSTRAINT FK_PARTTIME_WORKER
        FOREIGN KEY (WorkID)
        REFERENCES WORKERS(WorkID)
);

-- VENDORS
CREATE TABLE VENDORS (
    VendID NUMBER PRIMARY KEY,
    VendName VARCHAR2(100) NOT NULL,
    VendAddress VARCHAR2(200),
    VendPhoneNum VARCHAR2(20)
);

-- CONTAINERS
CREATE TABLE CONTAINERS (
    ContID NUMBER PRIMARY KEY,
    ContName VARCHAR2(100),
    ContDate DATE,
    ContColour VARCHAR2(50)
);

-- PRODUCTS
CREATE TABLE PRODUCTS (
    ProdID NUMBER PRIMARY KEY,
    ProdName VARCHAR2(100) NOT NULL,
    Price NUMBER(10,2),
    ProdType VARCHAR2(50),
    SalesPrice NUMBER(10,2),
    ContID NUMBER
);

-- INVENTORY
CREATE TABLE INVENTORY (
    ProdID NUMBER,
    ContID NUMBER,
    Qty NUMBER,
    PRIMARY KEY (ProdID, ContID),
    CONSTRAINT FK_INV_PRODUCT
        FOREIGN KEY (ProdID)
        REFERENCES PRODUCTS(ProdID),
    CONSTRAINT FK_INV_CONTAINER
        FOREIGN KEY (ContID)
        REFERENCES CONTAINERS(ContID)
);

-- ORDERS
CREATE TABLE ORDERS (
    OrderID NUMBER PRIMARY KEY,
    OrderDate DATE,
    CustID NUMBER NOT NULL,
    WorkID NUMBER NOT NULL,
    CONSTRAINT FK_ORDER_CUSTOMER
        FOREIGN KEY (CustID)
        REFERENCES CUSTOMER(CustID),
    CONSTRAINT FK_ORDER_WORKER
        FOREIGN KEY (WorkID)
        REFERENCES WORKERS(WorkID)
);

-- ORDER_PRODUCTS
CREATE TABLE ORDER_PRODUCTS (
    OrderID NUMBER,
    ProdID NUMBER,
    Qty NUMBER,
    PRIMARY KEY (OrderID, ProdID),
    CONSTRAINT FK_OP_ORDER
        FOREIGN KEY (OrderID)
        REFERENCES ORDERS(OrderID),
    CONSTRAINT FK_OP_PRODUCT
        FOREIGN KEY (ProdID)
        REFERENCES PRODUCTS(ProdID)
);

-- PURCHASE
CREATE TABLE PURCHASE (
    PurchID NUMBER PRIMARY KEY,
    PurchDate DATE,
    WorkID NUMBER NOT NULL,
    VendID NUMBER NOT NULL,
    CONSTRAINT FK_PURCHASE_WORKER
        FOREIGN KEY (WorkID)
        REFERENCES WORKERS(WorkID),
    CONSTRAINT FK_PURCHASE_VENDOR
        FOREIGN KEY (VendID)
        REFERENCES VENDORS(VendID)
);

-- PURCHASE_PRODUCT
CREATE TABLE PURCHASE_PRODUCT (
    PurchID NUMBER,
    ProdID NUMBER,
    Qty NUMBER,
    PRIMARY KEY (PurchID, ProdID),
    CONSTRAINT FK_PP_PURCHASE
        FOREIGN KEY (PurchID)
        REFERENCES PURCHASE(PurchID),
    CONSTRAINT FK_PP_PRODUCT
        FOREIGN KEY (ProdID)
        REFERENCES PRODUCTS(ProdID)
);