-- Junction / child tables first
TRUNCATE TABLE PURCHASE_PRODUCT;
TRUNCATE TABLE ORDER_PRODUCTS;
TRUNCATE TABLE INVENTORY;

-- Parent tables next
TRUNCATE TABLE PURCHASE;
TRUNCATE TABLE ORDERS;
TRUNCATE TABLE PRODUCTS;
TRUNCATE TABLE CONTAINERS;
TRUNCATE TABLE VENDORS;
TRUNCATE TABLE FULL_TIME_WORKERS;
TRUNCATE TABLE PART_TIME_WORKERS;
TRUNCATE TABLE WORKERS;
TRUNCATE TABLE CUSTOMERS;